#!/usr/bin/zsh
INFO=$(xwininfo -frame)
WIN_GEO=$(echo $INFO | grep -oEe 'geometry [0-9]+x[0-9]+' | grep -oEe '[0-9]+x[0-9]+')
WIN_XY=$(echo $INFO | grep -oEe 'Corners:\s+\+[0-9]+\+[0-9]+' | grep -oEe '[0-9]+\+[0-9]+' | sed -e 's/\+/,/' )
# WIN_XY=$(echo $INFO | awk '/Corners:/ { split($2,OUT,/\+/); print OUT[2]","OUT[3]  }')

# echo "$INFO"
declare -p WIN_GEO 
declare -p WIN_XY

ffmpeg -f x11grab -y -framerate 30 -video_size $WIN_GEO -i :0.0+$WIN_XY -vcodec ffv1 output.avi
